app/vov/routes/web.php
<?php

use App\Notifications\DailyReport;
use Illuminate\Notifications\DatabaseNotification;
use Illuminate\Support\Facades\Route;

/**
 * Auth layout
 */
Route::post('/login', 'Auth\LoginController@loginUser')->name('login');
Route::post('/forgot', 'Auth\ForgotPasswordController@sendResetLinkEmail')
    // тут добавил мидл, потому что в контроллере есть вывод сообщений
    ->middleware('locale')
    ->name('forgot');
Route::get('/logout', 'Auth\LoginController@logoutUser')->name('logout');
/**
 * Admin layout
 */
// TODO[DaGlob] 27.06.2020 17:52: role:admin,big_boss,mini_boss - remove after start create admin board
Route::prefix('admin')->middleware(['auth', 'role:admin,big_boss,mini_boss', 'locale'])->group(function () {

    Route::any('/{any?}', 'Web\AdminController@index')->name('adminIndex')->where('any', '.*');
});
/**
 * Boss layout
 */
Route::prefix('dashboard')->middleware(['auth', 'role:admin,big_boss,mini_boss', 'locale'])->group(function () {
    Route::any('/{any?}', 'Web\AdminController@dashboard')->name('dashboardIndex')->where('any', '.*');
});



/*
 * Public zone
 */
/** config block / */
$langs = ['en', 'he', 'ru'];
$lang_rules = implode('|', $langs);
$pages = ['patrol', 'sos', 'miniguard', 'shifter', 'gatekeeper_and_digital_id'];
$pages_rules = implode('|', $pages);
/** / config block */
/** reset password block / */
Route::get('/reset_password/{token}/{email}/{lang?}', 'Auth\ResetPasswordController@showResetForm')
    ->middleware(['locale', 'guest'])
    ->where([
        'lang' => "({$lang_rules})",
    ])
    ->name('password.reset');
Route::post('/reset_password/', 'Auth\ResetPasswordController@reset')
    ->middleware('locale')
    ->where([
        'lang' => "({$lang_rules})",
    ])
    ->name('password.reset.post');
/** / reset password block */
Route::group(['middleware' => 'locale'], function () use ($lang_rules, $pages_rules) {

    Route::get('/{product_static_page}/{lang?}', 'Web\PagesController@product_static_page')
        ->where([
            'product_static_page' => "({$pages_rules})",
            'lang' => "({$lang_rules})",
        ])
        ->name('product_static_page');
    Route::get('/privacy/{product_privacy_page}/{lang?}', 'Web\PagesController@product_privacy_page')
        ->where([
            'product_privacy_page' => "({$pages_rules})",
            'lang' => "({$lang_rules})",
        ])
        ->name('product_privacy_page');
    /** ------------------------------------------- */
    Route::get('/privacy_policy/{lang?}', 'Web\PagesController@privacy_policy')
        ->where(['lang' => "({$lang_rules})"])
        ->name('privacy_policy');
    /** ------------------------------------------- */
    Route::get('/termofuse/{lang?}', 'Web\PagesController@termofuse')
        ->where(['lang' => "({$lang_rules})"])
        ->name('termofuse');
    /** ------------------------------------------- */
    Route::get('/{lang?}', 'Web\PagesController@index')
        ->where(['lang' => "({$lang_rules})"])
        ->name('index');
}
);
Route::group(['middleware' => 'auth'], function () {

    Route::any('/searchdata/{lang?}', 'Api\PdfController@search')->name('search.data');
    Route::get('/downloadPdf/{id}', 'Api\PdfController@downlaod')->name('downloadPdf');
    Route::get( '/qr/{id}', 'Web\QrController@index' )->where('id', '[0-9]+')->name('QR');
    Route::get( '/qr/current', 'Web\QrController@current' )->name( 'currentQR' );
    Route::get('/barcodes/{lang}/{download?}', 'Api\BarcodeController@indexPrint');
});

Route::post('/action/sendmessage', 'Web\ContactController@store')->name('send_message');

if (config('app.env') !== 'production') {
    /** developers tools */
    Route::get('/invoice/{id}', function ($id) {
        if (!$notify = DatabaseNotification::find($id)) {
            abort('404');
        }

        $user = $notify->notifiable()->first();
        return (new DailyReport($notify->data['from'], $notify->data['to'], $notify->data['data'], true))
            ->toMail($user);
    });
}

app/vov/app/Models/Barcode.php
<?php

namespace App\Models;

use Illuminate\Support\Str;
use App\Traits\HebrewFields;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Jenssegers\Mongodb\Eloquent\HybridRelations;
use Illuminate\Database\Eloquent\Builder;
use QrCode as QrGenerator;

class Barcode extends Model
{
    use HybridRelations;
    use HebrewFields;
    //
    protected $casts = [
        'additional' => 'JSON'
    ];

    protected $table = 'barcodes';
    protected $connection = 'mysql';
    protected $visible = [
        'id', 'name', 'location', 'facility_id', 'facility', 'additional', 'qr_string', 'start_patrol_name'
    ];

    protected $fillable = [
        'name', 'location', 'user_id', 'facility_id', 'additional', 'start_patrol_name'
    ];

    public function facility()
    {
        return $this->belongsTo(MongoFacilitiesQrModel::class,'facility_id','owner_id');
    }

    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('user_id', function (Builder $builder) {
            $currentUserId = Auth::id();
            $builder->where('user_id', $currentUserId);
        });

    }

    public function updateQrString($isLast = false)
    {
        $hebrewPercents = [
            0 => 'אאא',
            10 => 'בבב',
            20 => 'גגג',
            30 => 'דדד',
            40 => 'ההה',
            50 => 'ווו',
            60 => 'זזז',
            70 => 'חחח',
            80 => 'טטט',
            90 => 'ייי',
            100 => 'כככ'
        ];

        $qrString['name'] = '_'.$this->name;
        $qrString['syr'] = '_';
        $qrString['open_questions'] = '';
        $qrString['predefined_questions'] = '';
        $qrString['reminder'] = '';

        if($this->facility->is_sayar){
            $qrString['syr'] = '*SYR*<'.$this->facility->facility_name.'>_';
        }

        if($this->is_last || $isLast) {
            $this->qr_string = $qrString['name'].$qrString['syr'].'*END*';
            return;
        }

        $questions = $this->additional;

        $haveOpenQuestions = isset($questions['open_questions']) && count($questions['open_questions']) > 0;
        $havePredefinedQuestions = isset($questions['predefined_questions']) && count($questions['predefined_questions']) > 0;

        if($haveOpenQuestions){
            $qs = '';
            $hints = '';
            foreach ($questions['open_questions'] as $open_question) {
                $qs .= $open_question['question'].';';
                if(isset($open_question['hint']) && $open_question['hint'] !== ''){
                    $hints .= $open_question['hint'].';';
                } else {
                    $hints .= ';';
                }
            }
            $qs = rtrim($qs, ';');
            $hints = rtrim($hints, ';');

            $delimiter = '&-&';

            if($havePredefinedQuestions) {
                $delimiter = '/';
            }

            $qrString['open_questions'] = '{Q:'.$qs . $delimiter . 'Hn:'.$hints.'}';
        }

        if($havePredefinedQuestions) {

            $questionsAll = [];
            $answersAll = [];

            foreach ($questions['predefined_questions'] as $questionIndex => $predefined_question) {

                $isHebrew = $this->isHebrew($predefined_question['question']);

                $questionsAll[] = $predefined_question['question'];

                $questionAnswers = [];

                foreach ($predefined_question['answers'] as $answerIndex => $answer) {

                    $percentVal = $isHebrew ? $hebrewPercents[round($answer['percent']/10)*10] : '('.$answer['percent'].'%)';

                    $answerText = $isHebrew ?
                        $this->makeHebrewLine($answer['answer'], $percentVal) :
                        $this->makeDefaultLine($answer['answer'], $percentVal);

                    if(!$answerIndex && !$questionIndex) {
                        if($isHebrew) $answerText = 'מחק.זה;' . $answerText;
                        else $answerText = 'delete.this;' . $answerText;
                    }

                    $questionAnswers[] = $answerText;
                }

                $answersAll[] = 'An' . ($questionIndex + 1) . ':' . implode(';', $questionAnswers);
            }

            if($this->isHebrew($questionsAll[0])) $questionsAll = array_reverse($questionsAll);

            $questionsAll = implode(';', $questionsAll);
            $answersAll = '/' . implode('/', $answersAll);

            $qrString['predefined_questions'] = $questionsAll . $answersAll;
        }

        $qrQuestions = '';

        if($haveOpenQuestions && $havePredefinedQuestions) {
            $qrQuestions = '[reg_check/Q:' . $qrString['predefined_questions'] . ']';
            $qrQuestions .= $qrString['open_questions'];
        }
        elseif($haveOpenQuestions) {
            $qrQuestions = '[reg_check/$$$' . $qrString['open_questions'] . ']';
        }
        elseif($havePredefinedQuestions) {
            $qrQuestions = '[reg_check/Q:' . $qrString['predefined_questions'] . ']';
        }

        if(isset($questions['reminder']) && $questions['reminder'] !== ''){
            $qrString['reminder'] = '[remind_check/R:'.$questions['reminder'].']';
        }

        if(isset($this->start_patrol_name) && $this->start_patrol_name == 1){
            $this->qr_string = $qrString['name'].'_[start_patrol_name]';
        } else {
            $this->qr_string = $qrString['name'] . $qrString['syr'] . $qrQuestions . $qrString['reminder'];
        }
    }

    private function isHebrew($string)
    {
        return preg_match("/\p{Hebrew}/u", $string);
    }

    private function makeDefaultLine($answer, $percent)
    {
        return $answer . $percent;
    }

    private function makeHebrewLine($answer, $percent)
    {
        return hebrev("{$answer} {$percent}");
    }

    public function checkSize() {
        return mb_strlen($this->qr_string, '8bit')<=2500;
    }

    public function updateQrImg($isCurrent = false)
    {
        if($this->checkSize()) {
            $qr = QrGenerator::format('svg')->encoding('UTF-8')->size(400)->generate($this->qr_string);
            $name = $isCurrent ? 'current' . $this->user_id : 'qr_' . $this->id;
            \Storage::disk('public')->put('/qrs/'.$name.'.svg', $qr);
        }
    }

    public function getQrCodeImgName()
    {
        return 'qr_'.$this->id.'.svg';
    }

    public function getNamePdfAttribute() {
        return $this->hebrewField($this->name);
    }

    public function getLocationPdfAttribute() {
        return $this->hebrewField($this->location);
    }

    public function getIsLastAttribute() {
        $lastBarcode = Barcode::where('facility_id', $this->facility_id)->orderBy('id', 'desc')->first();
        return $lastBarcode && $lastBarcode->id==$this->id;
    }
}

app/vov/app/Models/MongoFacilitiesQrModel.php
<?php

namespace App\Models;

use App\Traits\HebrewFields;
use DateTimeImmutable;
use DateTimeInterface;
use Exception;
use Illuminate\Support\Collection;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;
use Jenssegers\Mongodb\Eloquent\SoftDeletes;

class MongoFacilitiesQrModel extends Eloquent {

    use HebrewFields;

    public    $primaryKey = 'owner_id';
    public    $connection = 'mongodb';
    public    $collection = 'Facilities';
    protected $visible    = [
        'facility_name',
        'is_sayar'
    ];

    protected function mbStrrev(string $string, string $encoding = null) {
        $chars = mb_str_split($string, 1, $encoding ?: mb_internal_encoding());
        return implode('', array_reverse($chars));
    }

    protected function isRtl($string) {
        $rtlCharsPattern = '/[\x{0590}-\x{05ff}\x{0600}-\x{06ff}]/u';
        return preg_match($rtlCharsPattern, $string);
    }


    public function getFacilityNamePdfAttribute() {
        return $this->hebrewField($this->facility_name);
    }

}

app/vov/app/Http/Controllers/Api/BarcodeController.php
<?php

namespace App\Http\Controllers\Api;

use App;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\BarcodeRequest;
use App\Models\Barcode;
use Illuminate\Http\Request;
use PDF;
use App\Http\Controllers\Controller;
use App\Models\MongoFacilitiesModel;

class BarcodeController extends Controller
{
    private function prepare_index(Request $request)
    {
        $qrs = Barcode::with('facility');
        $facility_id = $request->get('facility_id');
        if ($facility_id) {
            $qrs->where('facility_id', $facility_id);
            sleep(2);
        }
        return $qrs;
    }

    public function index(Request $request)
    {

        $qrs = $this->prepare_index($request);
        return $qrs->get();
    }

    public function indexPrint(Request $request, $lang = 'en', $download = null)
    {
        App::setLocale($lang);
        $barcodes = $this->prepare_index($request);
        if ($request->get('page') == 'all') {
            $barcodes = $barcodes->get();
        } else {
            $barcodes = $barcodes->paginate(16);
        }

        $direction = $request->get('direction', 'ltr');
        if ($download && $download === 'download') {
            $facility_name = MongoFacilitiesModel::whereOwnerId($request->get('facility_id'))->first()->facility_name;
            $viewName = $direction == 'rtl' ? 'barcodes.pdf_rtl' : 'barcodes.pdf';
            $pdf = PDF::setOptions(['isHtml5ParserEnabled' => true, 'isRemoteEnabled' => true, 'chroot'  => base_path(),])
                ->loadView($viewName, ['barcodes' => $barcodes, 'direction' => $direction]);
            return $pdf->download($facility_name . '.pdf');
            //            return view('barcodes.pdf2', ['barcodes' => $barcodes, 'direction' => $direction]);
        } else if (!$download) {
            return view('barcodes.print', ['barcodes' => $barcodes, 'direction' => $direction]);
        } else {
            return redirect('/');
        }
    }

    public function store(BarcodeRequest $request)
    {
        return DB::transaction(function () use ($request) {

            $input = $request->post();
            $input['user_id'] = Auth::id();

            $barcode = Barcode::query()->create($input);

            return response()->json([
                'message' => 'Success',
                'id' => $barcode->id
            ]);
        });
    }

    public function updateCurrent(Request $request)
    {
        if ($request['name'] == null) $request['name'] = '123';

        $barcode =  new Barcode($request->post());
        $barcode->user_id = Auth::id();
        $barcode->updateQrString($request->post('is_last'));
        $barcode->updateQrImg(true);
        if ($barcode) {
            if ($barcode->checkSize()) {
                return response()->json(['message' => 'Success']);
            } else {
                return response()->json(['message' => 'Error'], 413);
            }
        }
        return response()->json(['message' => 'Error'], 400);
    }

    public function update(BarcodeRequest $request, Barcode $barcode)
    {

        if ($barcode) {

            $barcode->fill($request->post());
            $barcode->updateQrString();
            $barcode->updateQrImg();
            $barcode->save();
            if ($barcode) {
                return response()->json(['message' => 'Success']);
            }
        }
        return response()->json(['message' => 'Error'], 200);
    }

    public function delete($id)
    {
        //$user_id = \Auth::id();
        $barcode = Barcode::where('id', $id);
        if ($barcode) {
            $barcode->delete();
            return response()->json(['message' => 'Success', 'id' => $id]);
        }
        return response()->json(['message' => 'Error'], 400);
    }

    public function show($id)
    {
        $barcode = Barcode::where('id', $id)->with('facility')->first();
        if ($barcode) {
            return $barcode;
        } else {
            return response()->json(['message' => 'Error'], 400);
        }
    }

    public function makeBarcodes()
    {
        /**
         * @var $barcode Barcode
         */
        $barcodes = factory(Barcode::class, 100)->create();
        foreach ($barcodes as $barcode) {
            $barcode->updateQrString();
            $barcode->updateQrImg();
            $barcode->save();
        }
        return ['message' => '100 barcodes was added'];
    }
}

app/vov/resources/views/barcodes/pdf.blade.php
<!DOCTYPE html>
<html lang="{{app()->getLocale()}}">
<head>
    <meta charset=utf-8>
    <meta http-equiv=X-UA-Compatible content="IE=edge">
    <meta name=viewport content="width=device-width,initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel=icon href={{asset('images/fav-icon/icon1.png')}}>
    @php
        if(!isset($page_title) or $page_title=="")
        {
         echo '<title>IRONMAX</title>';
        }
        else{
         echo '<title>'.$page_title.' - IRONMAX</title>';
        }
    @endphp
    <style>
        @page{
            margin: 0;
        }
        body{
            font-family: firefly, DejaVu Sans, sans-serif;
            font-size: 10px;
            /*direction: {{ $direction }};*/
        }
        .qrs{
            width: 90%;
            margin: 0px auto;
        }
        .qr{
            border: 1px solid black;
            height: 235px;
            width: 23%;
            padding: 0px 10px;
            margin-left: 5px;
            margin-right: 5px;
            vertical-align: top;
            direction: {{ $direction }};
        }
        .qr-empty {
            border-color: #fff;
        }
        .qr-img img{
            width: 92px;
            height: auto;
        }
        .logo {
            text-align: center;
            /*margin: 9px 0px 12px;*/
            /*margin: 15px 0px;*/
            margin: 14px 0px 17px;
        }
        .qr-line {
            margin-top: 22px;
            height: 0;
            border-top: 1px solid #000;
        }
        .qr-img{
            text-align: center;
        }
        .facility img, .qr-name img, .location img{
            padding-right: 5px;
        }
        .facility, .qr-name, .location{
            /*text-align: justify;*/
        }
        .qr-name, .location{
            padding-top: 5px;
            line-height: 0.9;
        }
        .two-lines {
            display: block;  or inline-block
            text-overflow: ellipsis;
            word-wrap: break-word;
            overflow: hidden;
            max-height: 2.7em;
            line-height: 0.9em;
        }
    </style>
</head>
<body>
<table class="qrs" cellspacing="10" style="margin-top: 20px;">

    <tr>
        @php
            $i = 0;
        @endphp
        @foreach($barcodes as $barcode)
            <td class="qr">
                <table style="width: 100%;">
                    <tr>
                        <td>
                            <div class="logo">
                                <img width="92" src="{{public_path('images/qr/logo.png')}}" alt="">
                            </div>
                            <div class="qr-img">
                                <img src="{{public_path('/storage/qrs/'.$barcode->getQrCodeImgName())}}" alt="">
                            </div>
                            <!--<hr/>-->
                            <div class="qr-line"></div>
                        </td>
                    </tr>
                    <tr>
                        <td style="vertical-align: middle; height: 82px;">
                            <table style="padding: 0; margin: -3px auto 0px;border: none; vertical-align: top;">
                                <tbody>
                                <tr>
                                    <td style="text-align: center; padding: 3px 0; vertical-align: top;"><img width="10" height="11" src="{{public_path('images/qr/icon-1.png')}}" alt=""/></td>
                                    <td >{{$barcode->facility->facility_name_pdf}}</td>
                                </tr>
                                <tr>
                                    <td style="text-align: center; padding: 3px 0; vertical-align: top;"><img width="10" height="10" src="{{public_path('/images/qr/icon-2.png')}}" alt=""/></td>
                                    <td><div class="two-lines" style="hyphens: auto;word-break: break-all;">{{$barcode->name_pdf}}@if($barcode->is_last) ({{__('barcodes.last')}})@endif</div></td>
                                </tr>
                                @if($barcode->location!='')
                                <tr>
                                    <td style="text-align: center; padding: 3px 0; vertical-align: top;"><img width="8" height="11" src="{{public_path('/images/qr/icon-3.png')}}" alt=""/></td>
                                    <td><div class="two-lines">{{$barcode->location_pdf}}</div></td>
                                </tr>
                                @endif
                                </tbody>
                            </table>
                        </td>
                    </tr>
                </table>
            </td>
            @php
                $i++;
            @endphp
            @if($i === count($barcodes) && $i % 4 !== 0)
                @for($j=0; $j<(4 - ($i % 4)); $j++)
                    <td class="qr qr-empty"></td>
                @endfor
            @endif
            @if($i % 4 === 0)
    </tr>
    @if($i < count($barcodes))
        <tr>
            @endif
            @endif
            @endforeach
        </tr>
</table>
</body>
</html>

app/vov/resources/views/barcodes/pdf_rtl.blade.php
<!DOCTYPE html>
<html lang="{{app()->getLocale()}}">
<head>
    <meta charset=utf-8>
    <meta http-equiv=X-UA-Compatible content="IE=edge">
    <meta name=viewport content="width=device-width,initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel=icon href={{asset('images/fav-icon/icon1.png')}}>
    @php
        if(!isset($page_title) or $page_title=="")
        {
         echo '<title>IRONMAX</title>';
        }
        else{
         echo '<title>'.$page_title.' - IRONMAX</title>';
        }
    @endphp
    <style>
        @page{
            margin: 0;
        }
        body{
            font-family: firefly, DejaVu Sans, sans-serif;
            font-size: 10px;
            /*direction: {{ $direction }};*/
        }
        .qrs{
            width: 90%;
            margin: 0px auto;
        }
        .qr{
            border: 1px solid black;
            height: 235px;
            width: 23%;
            padding: 0px 10px;
            margin-left: 5px;
            margin-right: 5px;
            vertical-align: top;
            direction: {{ $direction }};
        }
        .qr-empty {
            border-color: #fff;
        }
        .qr-img img{
            width: 92px;
            height: auto;
        }
        .logo {
            text-align: center;
            /*margin: 9px 0px 12px;*/
            /*margin: 15px 0px;*/
            margin: 14px 0px 17px;
        }
        .qr-line {
            margin-top: 22px;
            height: 0;
            border-top: 1px solid #000;
        }
        .qr-img{
            text-align: center;
        }
        .facility img, .qr-name img, .location img{
            padding-right: 5px;
        }
        .facility, .qr-name, .location{
            /*text-align: justify;*/
        }
        .qr-name, .location{
            padding-top: 5px;
            line-height: 0.9;
        }
        .two-lines {
            display: block;  or inline-block
            text-overflow: ellipsis;
            word-wrap: break-word;
            overflow: hidden;
            max-height: 2.7em;
            line-height: 0.9em;
        }
    </style>
</head>
<body>
<table class="qrs" cellspacing="10" style="margin-top: 20px;">

    <tr>
        @php
            $i = 0;
        @endphp
        @foreach($barcodes as $barcode)
            <td class="qr">
                <table style="width: 100%;">
                    <tr>
                        <td>
                            <div class="logo">
                                <img width="92" src="{{public_path('images/qr/logo.png')}}" alt="">
                            </div>
                            <div class="qr-img">
                                <img src="{{public_path('/storage/qrs/'.$barcode->getQrCodeImgName())}}" alt="">
                            </div>
                            <!--<hr/>-->
                            <div class="qr-line"></div>
                        </td>
                    </tr>
                    <tr>
                        <td style="vertical-align: middle; height: 82px;">
                            <table style="padding: 0; margin: -3px auto 0px;border: none; vertical-align: top; text-align: right;">
                                <tbody>
                                <tr>
                                    <td>{{$barcode->facility->facility_name_pdf}}</td>
                                    <td style="text-align: center; padding: 3px 0;"><img width="10" height="11" src="{{public_path('images/qr/icon-1.png')}}" alt=""/></td>
                                </tr>
                                <tr>
                                    <td><div class="two-lines" style="hyphens: auto;word-break: break-all;">@if($barcode->is_last)({{__('barcodes.last')}}) @endif{{$barcode->name_pdf}}</div></td>
                                    <td style="text-align: center; padding: 3px 0; padding-top: 5px;"><img width="10" height="10" src="{{public_path('/images/qr/icon-2.png')}}" alt=""/></td>
                                </tr>
                                @if($barcode->location!='')
                                    <tr>
                                        <td><div class="two-lines">{{$barcode->location_pdf}}</div></td>
                                        <td style="text-align: center; padding: 3px 0; vertical-align: top;"><img width="8" height="11" src="{{public_path('/images/qr/icon-3.png')}}" alt=""/></td>
                                    </tr>
                                @endif
                                </tbody>
                            </table>
                        </td>
                    </tr>
                </table>
            </td>
            @php
                $i++;
            @endphp
            @if($i === count($barcodes) && $i % 4 !== 0)
                @for($j=0; $j<(4 - ($i % 4)); $j++)
                    <td class="qr qr-empty"></td>
                @endfor
            @endif

            @if($i % 4 === 0)
    </tr>
    @if($i < count($barcodes))
        <tr>
            @endif
            @endif
            @endforeach
        </tr>
</table>
</body>
</html>